// src/hooks/useIdioma.js
import { useState, useEffect, createContext, useContext } from 'react'

// ─── DICIONÁRIO COMPLETO ────────────────────────────────────────
// Abrange: sidebar, títulos, botões, labels, mensagens de UI
export const TRADUCOES = {
  // ── Secções sidebar ──
  principal:      { pt:'Principal',      br:'Principal',       en:'Main',            es:'Principal' },
  desporto:       { pt:'Desporto',       br:'Esporte',         en:'Sport',           es:'Deporte' },
  gestao:         { pt:'Gestão',         br:'Gestão',          en:'Management',      es:'Gestión' },
  analise:        { pt:'Análise',        br:'Análise',         en:'Analytics',       es:'Análisis' },
  social:         { pt:'Social',         br:'Social',          en:'Social',          es:'Social' },
  sistema:        { pt:'Sistema',        br:'Sistema',         en:'System',          es:'Sistema' },
  // ── Módulos ──
  dashboard:      { pt:'Pombal Hoje',    br:'Colombário Hoje', en:'Loft Today',      es:'Palomar Hoy' },
  pombos:         { pt:'Pombos',         br:'Pombos Correio',  en:'Pigeons',         es:'Palomas' },
  pombal:         { pt:'Pombais',        br:'Colombários',     en:'Lofts',           es:'Palomares' },
  provas:         { pt:'Provas',         br:'Corridas',        en:'Races',           es:'Carreras' },
  treinos:        { pt:'Treinos',        br:'Treinos',         en:'Training',        es:'Entrenamientos' },
  calendario:     { pt:'Calendário',     br:'Calendário',      en:'Calendar',        es:'Calendario' },
  checklist:      { pt:'Checklist',      br:'Checklist',       en:'Checklist',       es:'Lista de tareas' },
  saude:          { pt:'Saúde',          br:'Saúde',           en:'Health',          es:'Salud' },
  reproducao:     { pt:'Reprodução',     br:'Reprodução',      en:'Breeding',        es:'Cría' },
  pedigree:       { pt:'Pedigree',       br:'Pedigree',        en:'Pedigree',        es:'Pedigrí' },
  casais:         { pt:'Casais IA',      br:'Casais IA',       en:'AI Pairs',        es:'Parejas IA' },
  alimentacao:    { pt:'Alimentação',    br:'Alimentação',     en:'Feeding',         es:'Alimentación' },
  tratamentos:    { pt:'Tratamentos',    br:'Tratamentos',     en:'Treatments',      es:'Tratamientos' },
  financas:       { pt:'Finanças',       br:'Finanças',        en:'Finances',        es:'Finanzas' },
  relatorios:     { pt:'Relatórios',     br:'Relatórios',      en:'Reports',         es:'Informes' },
  analiticas:     { pt:'Analíticas',     br:'Analíticas',      en:'Analytics',       es:'Analíticas' },
  rastreioForma:  { pt:'Rastreio Forma', br:'Rastreio Forma',  en:'Form Tracking',   es:'Seguimiento' },
  epoca:          { pt:'Época',          br:'Época',           en:'Season',          es:'Temporada' },
  meteorologia:   { pt:'Meteorologia',   br:'Meteorologia',    en:'Weather',         es:'Meteorología' },
  comunidade:     { pt:'Comunidade',     br:'Comunidade',      en:'Community',       es:'Comunidad' },
  mensagens:      { pt:'Mensagens',      br:'Mensagens',       en:'Messages',        es:'Mensajes' },
  clubes:         { pt:'Clubes',         br:'Clubes',          en:'Clubs',           es:'Clubes' },
  leiloes:        { pt:'Leilões',        br:'Leilões',         en:'Auctions',        es:'Subastas' },
  marketplace:    { pt:'Marketplace',    br:'Marketplace',     en:'Marketplace',     es:'Mercado' },
  ligas:          { pt:'Ligas',          br:'Ligas',           en:'Leagues',         es:'Ligas' },
  planos:         { pt:'Planos',         br:'Planos',          en:'Plans',           es:'Planes' },
  importar:       { pt:'Importar',       br:'Importar',        en:'Import',          es:'Importar' },
  exportar:       { pt:'Exportar',       br:'Exportar',        en:'Export',          es:'Exportar' },
  afiliados:      { pt:'Afiliados',      br:'Afiliados',       en:'Affiliates',      es:'Afiliados' },
  perfil:         { pt:'Perfil',         br:'Perfil',          en:'Profile',         es:'Perfil' },
  // ── Terminologia columbófila ──
  pombo:          { pt:'Pombo',          br:'Pombo Correio',   en:'Pigeon',          es:'Paloma' },
  pombalSing:     { pt:'Pombal',         br:'Colombário',      en:'Loft',            es:'Palomar' },
  anilha:         { pt:'Anilha',         br:'Argola',          en:'Ring',            es:'Anilla' },
  efectivo:       { pt:'Efectivo',       br:'Plantel',         en:'Stock',           es:'Efectivo' },
  prova:          { pt:'Prova',          br:'Corrida',         en:'Race',            es:'Carrera' },
  percentil:      { pt:'Percentil',      br:'Percentil',       en:'Percentile',      es:'Percentil' },
  velocidade:     { pt:'Velocidade',     br:'Velocidade',      en:'Speed',           es:'Velocidad' },
  fundo:          { pt:'Fundo',          br:'Fundo',           en:'Long dist.',      es:'Fondo' },
  federacao:      { pt:'Federação (FPC)',br:'Fed. (FENAC)',     en:'Federation',      es:'Federación' },
  borrachinho:    { pt:'Borrachinho',    br:'Pinto/Filhote',   en:'Squab',           es:'Pichón' },
  cacifo:         { pt:'Cacifo',         br:'Gaiola/Ninho',    en:'Box/Nest',        es:'Nidal' },
  columbofilo:    { pt:'Columbófilo',    br:'Colombófilo',     en:'Pigeon fancier',  es:'Colombófilo' },
  linhagem:       { pt:'Linhagem',       br:'Linhagem',        en:'Bloodline',       es:'Línea genética' },
  ninhada:        { pt:'Ninhada',        br:'Ninhada',         en:'Clutch',          es:'Nidada' },
  especialidade:  { pt:'Especialidade',  br:'Especialidade',   en:'Specialty',       es:'Especialidad' },
  // ── UI — Botões e acções ──
  guardar:        { pt:'Guardar',        br:'Salvar',          en:'Save',            es:'Guardar' },
  cancelar:       { pt:'Cancelar',       br:'Cancelar',        en:'Cancel',          es:'Cancelar' },
  eliminar:       { pt:'Eliminar',       br:'Excluir',         en:'Delete',          es:'Eliminar' },
  editar:         { pt:'Editar',         br:'Editar',          en:'Edit',            es:'Editar' },
  novo:           { pt:'Novo',           br:'Novo',            en:'New',             es:'Nuevo' },
  nova:           { pt:'Nova',           br:'Nova',            en:'New',             es:'Nueva' },
  adicionar:      { pt:'Adicionar',      br:'Adicionar',       en:'Add',             es:'Añadir' },
  pesquisar:      { pt:'Pesquisar',      br:'Pesquisar',       en:'Search',          es:'Buscar' },
  filtrar:        { pt:'Filtrar',        br:'Filtrar',         en:'Filter',          es:'Filtrar' },
  carregar:       { pt:'Carregar',       br:'Carregar',        en:'Load',            es:'Cargar' },
  descarregar:    { pt:'Descarregar',    br:'Baixar',          en:'Download',        es:'Descargar' },
  importar2:      { pt:'Importar',       br:'Importar',        en:'Import',          es:'Importar' },
  exportar2:      { pt:'Exportar',       br:'Exportar',        en:'Export',          es:'Exportar' },
  confirmar:      { pt:'Confirmar',      br:'Confirmar',       en:'Confirm',         es:'Confirmar' },
  fechar:         { pt:'Fechar',         br:'Fechar',          en:'Close',           es:'Cerrar' },
  ver:            { pt:'Ver',            br:'Ver',             en:'View',            es:'Ver' },
  partilhar:      { pt:'Partilhar',      br:'Compartilhar',    en:'Share',           es:'Compartir' },
  // ── UI — Estados e labels ──
  ativo:          { pt:'Activo',         br:'Ativo',           en:'Active',          es:'Activo' },

  // ── Dashboard ──
  bomDia:         { pt:'Bom dia',        br:'Bom dia',         en:'Good morning',   es:'Buenos días' },
  boaTarde:       { pt:'Boa tarde',       br:'Boa tarde',        en:'Good afternoon', es:'Buenas tardes' },
  boaNoite:       { pt:'Boa noite',       br:'Boa noite',        en:'Good evening',   es:'Buenas noches' },
  pombalHoje:     { pt:'Pombal Hoje',     br:'Colombário Hoje',  en:'Loft Today',     es:'Palomar Hoy' },
  activos:        { pt:'Activos',         br:'Ativos',           en:'Active',         es:'Activos' },
  casais2:        { pt:'Casais',          br:'Casais',           en:'Pairs',          es:'Parejas' },
  alertas:        { pt:'Alerta(s)',       br:'Alerta(s)',        en:'Alert(s)',        es:'Alerta(s)' },
  hoje:           { pt:'Hoje',            br:'Hoje',             en:'Today',          es:'Hoy' },
  semana:         { pt:'Esta semana',     br:'Esta semana',      en:'This week',      es:'Esta semana' },
  destaque:       { pt:'Destaque da Época',br:'Destaque da Época',en:'Season Highlight',es:'Destaque' },
  reproducaoActiva:{ pt:'Reprodução Activa',br:'Reprodução Ativa',en:'Active Breeding',es:'Cría activa' },
  acasalamentos:  { pt:'acasalamentos em curso',br:'acasalamentos em curso',en:'active pairs',es:'parejas activas' },
  ultimasProvas:  { pt:'Últimas Provas',  br:'Últimas Corridas', en:'Latest Races',   es:'Últimas Carreras' },
  verTodas:       { pt:'Ver todas →',     br:'Ver todas →',      en:'View all →',     es:'Ver todas →' },
  semProvas:      { pt:'Sem provas registadas', br:'Sem corridas',en:'No races yet',  es:'Sin carreras' },
  atenção:        { pt:'Atenção',         br:'Atenção',          en:'Attention',      es:'Atención' },
  emAtraso:       { pt:'Em atraso',       br:'Em atraso',        en:'Overdue',        es:'Atrasado' },
  emQueda:        { pt:'em queda',        br:'em queda',         en:'declining',      es:'en caída' },
  semSaude:       { pt:'Sem registo de saúde há', br:'Sem registo há', en:'No health record for', es:'Sin registro de salud hace' },
  dias:           { pt:'dias',            br:'dias',             en:'days',           es:'días' },
  tarefas:        { pt:'tarefa(s) em atraso',br:'tarefa(s) atrasada(s)',en:'overdue task(s)',es:'tarea(s) atrasada(s)' },
  scoreMediao:    { pt:'Score Médio',     br:'Score Médio',      en:'Avg. Score',     es:'Puntuación media' },
  saldo:          { pt:'Saldo',           br:'Saldo',            en:'Balance',        es:'Saldo' },
  registarChegada:{ pt:'Registar Chegada',br:'Registrar Chegada',en:'Log Arrival',   es:'Registrar Llegada' },
  registoSaude:   { pt:'Registo Saúde',  br:'Registro Saúde',   en:'Health Record',  es:'Registro Salud' },
  novoTreino:     { pt:'Novo Treino',     br:'Novo Treino',      en:'New Training',   es:'Nuevo Entrenamiento' },

  // ── Pombos ──
  addPombo:       { pt:'Adicionar Pombo', br:'Adicionar Pombo',  en:'Add Pigeon',     es:'Añadir Paloma' },
  editPombo:      { pt:'Editar Pombo',    br:'Editar Pombo',     en:'Edit Pigeon',    es:'Editar Paloma' },
  nenhum:         { pt:'Nenhum',          br:'Nenhum',           en:'None',           es:'Ninguno' },
  nenhumPombo:    { pt:'Sem pombos',      br:'Sem pombos',       en:'No pigeons',     es:'Sin palomas' },
  addPrimeiro:    { pt:'Adiciona o primeiro pombo ao teu efectivo', br:'Adicione o primeiro pombo', en:'Add your first pigeon', es:'Añade tu primera paloma' },
  pombalLabel:    { pt:'Pombal',          br:'Colombário',       en:'Loft',           es:'Palomar' },
  todosPombais:   { pt:'Todos os pombais',br:'Todos os colombários',en:'All lofts',   es:'Todos los palomares' },
  todos:          { pt:'Todos',           br:'Todos',            en:'All',            es:'Todos' },
  macho:          { pt:'Macho',           br:'Macho',            en:'Male',           es:'Macho' },
  femea:          { pt:'Fêmea',           br:'Fêmea',            en:'Female',         es:'Hembra' },
  vendidos:       { pt:'Vendidos',        br:'Vendidos',         en:'Sold',           es:'Vendidos' },
  externos:       { pt:'Externos',        br:'Externos',         en:'External',       es:'Externos' },
  linhagens:      { pt:'Linhagem',        br:'Linhagem',         en:'Bloodline',      es:'Línea genética' },
  nacimento:      { pt:'Nascimento',      br:'Nascimento',       en:'Birth',          es:'Nacimiento' },
  origem:         { pt:'Origem / Criador',br:'Origem / Criador', en:'Origin / Breeder',es:'Origen / Criador' },
  pai:            { pt:'Pai',             br:'Pai',              en:'Sire',           es:'Padre' },
  mae:            { pt:'Mãe',             br:'Mãe',              en:'Dam',            es:'Madre' },
  confirmarEliminar:{ pt:'Eliminar pombo?',br:'Excluir pombo?',  en:'Delete pigeon?', es:'¿Eliminar paloma?' },

  // ── Provas ──
  novaProva:      { pt:'Nova Prova',      br:'Nova Corrida',     en:'New Race',       es:'Nueva Carrera' },
  editProva:      { pt:'Editar Prova',    br:'Editar Corrida',   en:'Edit Race',      es:'Editar Carrera' },
  localSolta:     { pt:'Local de Solta',  br:'Local de Largada', en:'Release Point',  es:'Punto de suelta' },
  horaChegada:    { pt:'Hora de Chegada', br:'Hora de Chegada',  en:'Arrival Time',   es:'Hora de llegada' },
  posicao:        { pt:'Posição',         br:'Posição',          en:'Position',       es:'Posición' },
  nPombos:        { pt:'Nº de Pombos',    br:'Nº de Pombos',     en:'No. of Pigeons', es:'Nº de palomas' },
  encestamento:   { pt:'Encestamento',    br:'Encestamento',     en:'Basketing',      es:'Encestamiento' },
  resultados:     { pt:'Resultados',      br:'Resultados',       en:'Results',        es:'Resultados' },
  semResultados:  { pt:'Nenhum pombo encestado', br:'Nenhum pombo', en:'No pigeons basketed', es:'Sin palomas encestadas' },
  meteoProva:     { pt:'MeteoProva',      br:'MeteoProva',       en:'Race Weather',   es:'Clima Carrera' },
  rotaVoo:        { pt:'Rota de Voo',     br:'Rota de Voo',      en:'Flight Route',   es:'Ruta de Vuelo' },
  anexos:         { pt:'Anexos',          br:'Anexos',           en:'Attachments',    es:'Adjuntos' },
  carregar:       { pt:'Carregar',        br:'Carregar',         en:'Upload',         es:'Subir' },
  semAnexos:      { pt:'Sem anexos',      br:'Sem anexos',       en:'No attachments', es:'Sin adjuntos' },
  tipo:           { pt:'Tipo',            br:'Tipo',             en:'Type',           es:'Tipo' },
  velocidadeMedia:{ pt:'Vel. Média',      br:'Vel. Média',       en:'Avg. Speed',     es:'Vel. media' },

  // ── Reprodução ──
  novoAcasal:     { pt:'Novo Acasalamento',br:'Novo Acasalamento',en:'New Pair',      es:'Nueva Pareja' },
  editAcasal:     { pt:'Editar Acasalamento',br:'Editar',        en:'Edit Pair',      es:'Editar Pareja' },
  cacifo2:        { pt:'Cacifo / Ninho',  br:'Gaiola / Ninho',   en:'Box / Nest',     es:'Nidal' },
  dataPostura:    { pt:'Data de Postura', br:'Data de Postura',  en:'Laying Date',    es:'Fecha de puesta' },
  dataEclosao:    { pt:'Eclosão Prevista',br:'Eclosão Prevista', en:'Expected Hatch', en:'Eclosión prevista' },
  borrachinhos:   { pt:'Borrachinhos',    br:'Pinto/Filhote',    en:'Squabs',         es:'Pichones' },
  emProgresso:    { pt:'Em progresso',    br:'Em progresso',     en:'In progress',    es:'En curso' },
  concluido2:     { pt:'Concluído',       br:'Concluído',        en:'Completed',      es:'Completado' },
  casaisActivos:  { pt:'Casais Activos',  br:'Casais Ativos',    en:'Active Pairs',   es:'Parejas activas' },
  semCasais:      { pt:'Sem casais',      br:'Sem casais',       en:'No pairs',       es:'Sin parejas' },

  // ── Saúde ──
  novoRegisto:    { pt:'Novo Registo',    br:'Novo Registro',    en:'New Record',     es:'Nuevo Registro' },
  editRegisto:    { pt:'Editar Registo',  br:'Editar Registro',  en:'Edit Record',    es:'Editar Registro' },
  diagnostico:    { pt:'Diagnóstico',     br:'Diagnóstico',      en:'Diagnosis',      es:'Diagnóstico' },
  tratamento2:    { pt:'Tratamento',      br:'Tratamento',       en:'Treatment',      es:'Tratamiento' },
  medicamento:    { pt:'Medicamento',     br:'Medicamento',      en:'Medication',     es:'Medicación' },
  dose:           { pt:'Dose',            br:'Dose',             en:'Dose',           es:'Dosis' },
  duracao2:       { pt:'Duração (dias)',  br:'Duração (dias)',   en:'Duration (days)',es:'Duración (días)' },
  veterinario:    { pt:'Veterinário',     br:'Veterinário',      en:'Vet',            es:'Veterinario' },
  curado:         { pt:'Curado',          br:'Curado',           en:'Recovered',      es:'Curado' },
  emTratamento:   { pt:'Em tratamento',   br:'Em tratamento',    en:'Under treatment',es:'En tratamiento' },
  semHistorial:   { pt:'Sem historial',   br:'Sem histórico',    en:'No history',     es:'Sin historial' },
  todosOsPombos:  { pt:'Todos os pombos', br:'Todos os pombos',  en:'All pigeons',    es:'Todas las palomas' },


  // ── Tratamentos ──
  planoTratamento:  { pt:'Plano de Tratamento',  br:'Plano de Tratamento',  en:'Treatment Plan',      es:'Plan de Tratamiento' },
  novoPlano:        { pt:'Novo Plano',            br:'Novo Plano',           en:'New Plan',            es:'Nuevo Plan' },
  editPlano:        { pt:'Editar Plano',          br:'Editar Plano',         en:'Edit Plan',           es:'Editar Plan' },
  aplicar:          { pt:'Aplicar',               br:'Aplicar',              en:'Apply',               es:'Aplicar' },
  aplicado:         { pt:'Aplicado',              br:'Aplicado',             en:'Applied',             es:'Aplicado' },
  pendente2:        { pt:'Pendente',              br:'Pendente',             en:'Pending',             es:'Pendiente' },
  semana2:          { pt:'Semana',                br:'Semana',               en:'Week',                es:'Semana' },
  produto:          { pt:'Produto',               br:'Produto',              en:'Product',             es:'Producto' },
  produtos:         { pt:'Produtos',              br:'Produtos',             en:'Products',            es:'Productos' },
  dosagem:          { pt:'Dosagem',               br:'Dosagem',              en:'Dosage',              es:'Dosificación' },
  frequencia:       { pt:'Frequência',            br:'Frequência',           en:'Frequency',           es:'Frecuencia' },
  duracao3:         { pt:'Duração',               br:'Duração',              en:'Duration',            es:'Duración' },
  planoAtivo:       { pt:'Plano Activo',          br:'Plano Ativo',          en:'Active Plan',         es:'Plan Activo' },
  semPlanos:        { pt:'Sem planos de tratamento', br:'Sem planos',        en:'No treatment plans',  es:'Sin planes' },
  historico2:       { pt:'Histórico',             br:'Histórico',            en:'History',             es:'Historial' },
  registarAplicacao:{ pt:'Registar Aplicação',    br:'Registrar Aplicação',  en:'Log Application',     es:'Registrar Aplicación' },
  vitaminasSuple:   { pt:'Vitaminas/Suplementos', br:'Vitaminas/Suplementos',en:'Vitamins/Supplements',es:'Vitaminas/Suplementos' },
  desparasitacao:   { pt:'Desparasitação',        br:'Desparasitação',       en:'Deworming',           es:'Desparasitación' },
  vacinacao:        { pt:'Vacinação',             br:'Vacinação',            en:'Vaccination',         es:'Vacunación' },
  antibiotico:      { pt:'Antibiótico',           br:'Antibiótico',          en:'Antibiotic',          es:'Antibiótico' },

  // ── Alimentação ──
  stock2:           { pt:'Stock',                 br:'Estoque',              en:'Stock',               es:'Stock' },
  racao:            { pt:'Ração',                 br:'Ração',                en:'Feed',                es:'Pienso' },
  racoes:           { pt:'Rações',                br:'Rações',               en:'Feeds',               es:'Piensos' },
  mistura:          { pt:'Mistura',               br:'Mistura',              en:'Mix',                 es:'Mezcla' },
  fornecedor:       { pt:'Fornecedor',            br:'Fornecedor',           en:'Supplier',            es:'Proveedor' },
  quantidade2:      { pt:'Quantidade (kg)',        br:'Quantidade (kg)',       en:'Quantity (kg)',       es:'Cantidad (kg)' },
  consumoDiario:    { pt:'Consumo Diário',        br:'Consumo Diário',       en:'Daily Consumption',   es:'Consumo Diario' },
  stockAtual:       { pt:'Stock Actual',          br:'Stock Atual',          en:'Current Stock',       es:'Stock Actual' },
  stockMinimo:      { pt:'Stock Mínimo',          br:'Stock Mínimo',         en:'Min. Stock',          es:'Stock Mínimo' },
  alertaStock:      { pt:'Alerta de Stock Baixo', br:'Alerta de Estoque',    en:'Low Stock Alert',     es:'Alerta de Stock' },
  registarConsumo:  { pt:'Registar Consumo',      br:'Registrar Consumo',    en:'Log Consumption',     es:'Registrar Consumo' },
  reposicao:        { pt:'Reposição',             br:'Reposição',            en:'Restock',             es:'Reposición' },
  planoAlim:        { pt:'Plano Alimentar',       br:'Plano Alimentar',      en:'Feeding Plan',        es:'Plan Alimenticio' },
  semStock:         { pt:'Sem produtos em stock', br:'Sem estoque',          en:'No stock items',      es:'Sin stock' },
  categoriaAlim:    { pt:'Categoria',             br:'Categoria',            en:'Category',            es:'Categoría' },
  preco2:           { pt:'Preço (€)',             br:'Preço (€)',             en:'Price (€)',           es:'Precio (€)' },

  // ── Pedigree ──
  arvoreGeneal:     { pt:'Árvore Genealógica',    br:'Árvore Genealógica',   en:'Family Tree',         es:'Árbol Genealógico' },
  editarAnc:        { pt:'Editar Ancestral',      br:'Editar Ancestral',     en:'Edit Ancestor',       es:'Editar Ancestro' },
  ancestral:        { pt:'Ancestral',             br:'Ancestral',            en:'Ancestor',            es:'Ancestro' },
  avo:              { pt:'Avô/Avó',               br:'Avô/Avó',              en:'Grandparent',         es:'Abuelo/a' },
  bisavo:           { pt:'Bisavô/Bisavó',         br:'Bisavô/Bisavó',        en:'Great-grandparent',   es:'Bisabuelo/a' },
  carregarEfectivo: { pt:'Carregar do Efectivo',  br:'Carregar do Plantel',  en:'Load from Stock',     es:'Cargar del Efectivo' },
  descarregarPDF:   { pt:'Descarregar PDF',       br:'Baixar PDF',           en:'Download PDF',        es:'Descargar PDF' },
  semPomboSel:      { pt:'Selecciona um pombo para ver o pedigree', br:'Selecione um pombo', en:'Select a pigeon to view pedigree', es:'Selecciona una paloma' },
  pedigreeCompleto: { pt:'Pedigree Completo',     br:'Pedigree Completo',    en:'Full Pedigree',       es:'Pedigrí Completo' },
  conquistas2:      { pt:'Conquistas e Resultados',br:'Conquistas e Resultados',en:'Achievements & Results',es:'Logros y Resultados' },
  linhGenetica:     { pt:'Linhagem Genética',     br:'Linhagem Genética',    en:'Genetic Lineage',     es:'Línea Genética' },
  externo:          { pt:'Externo ao pombal',      br:'Externo ao plantel',   en:'External to loft',    es:'Externo al palomar' },

  // ── Checklist ──
  novaTarefa:       { pt:'Nova Tarefa',           br:'Nova Tarefa',          en:'New Task',            es:'Nueva Tarea' },
  editTarefa:       { pt:'Editar Tarefa',         br:'Editar Tarefa',        en:'Edit Task',           es:'Editar Tarea' },
  titulo2:          { pt:'Título',                br:'Título',               en:'Title',               es:'Título' },
  prioridade:       { pt:'Prioridade',            br:'Prioridade',           en:'Priority',            es:'Prioridad' },
  alta:             { pt:'Alta',                  br:'Alta',                 en:'High',                es:'Alta' },
  media2:           { pt:'Média',                 br:'Média',                en:'Medium',              es:'Media' },
  baixa:            { pt:'Baixa',                 br:'Baixa',                en:'Low',                 es:'Baja' },
  concluir:         { pt:'Concluir',              br:'Concluir',             en:'Complete',            es:'Completar' },
  reabrirTask:      { pt:'Reabrir',               br:'Reabrir',              en:'Reopen',              es:'Reabrir' },
  dataPrevista:     { pt:'Data Prevista',         br:'Data Prevista',        en:'Due Date',            es:'Fecha prevista' },
  semTarefas:       { pt:'Sem tarefas',           br:'Sem tarefas',          en:'No tasks',            es:'Sin tareas' },
  tarefasConcluidas:{ pt:'Concluídas',            br:'Concluídas',           en:'Completed',           es:'Completadas' },
  tarefasPendentes: { pt:'Pendentes',             br:'Pendentes',            en:'Pending',             es:'Pendientes' },
  tarefasAtraso:    { pt:'Em Atraso',             br:'Em Atraso',            en:'Overdue',             es:'Atrasadas' },
  recorrente:       { pt:'Recorrente',            br:'Recorrente',           en:'Recurring',           es:'Recurrente' },
  categoria2:       { pt:'Categoria',             br:'Categoria',            en:'Category',            es:'Categoría' },
  limpeza:          { pt:'Limpeza',               br:'Limpeza',              en:'Cleaning',            es:'Limpieza' },
  alimentacao2:     { pt:'Alimentação',           br:'Alimentação',          en:'Feeding',             es:'Alimentación' },
  veterinario2:     { pt:'Veterinário',           br:'Veterinário',          en:'Veterinary',          es:'Veterinario' },
  geral2:           { pt:'Geral',                 br:'Geral',                en:'General',             es:'General' },

  // ── Finanças ──
  novaTransacao:    { pt:'Nova Transacção',       br:'Nova Transação',       en:'New Transaction',     es:'Nueva Transacción' },
  receita:          { pt:'Receita',               br:'Receita',              en:'Income',              es:'Ingreso' },
  despesa:          { pt:'Despesa',               br:'Despesa',              en:'Expense',             es:'Gasto' },
  saldo2:           { pt:'Saldo',                 br:'Saldo',                en:'Balance',             es:'Saldo' },
  totalReceitas:    { pt:'Total Receitas',        br:'Total Receitas',       en:'Total Income',        es:'Total Ingresos' },
  totalDespesas:    { pt:'Total Despesas',        br:'Total Despesas',       en:'Total Expenses',      es:'Total Gastos' },
  categoriaFin:     { pt:'Categoria',             br:'Categoria',            en:'Category',            es:'Categoría' },
  vendaPombo:       { pt:'Venda de Pombo',        br:'Venda de Pombo',       en:'Pigeon Sale',         es:'Venta de Paloma' },
  compraPombo:      { pt:'Compra de Pombo',       br:'Compra de Pombo',      en:'Pigeon Purchase',     es:'Compra de Paloma' },
  inscricaoProva:   { pt:'Inscrição em Prova',    br:'Inscrição em Corrida', en:'Race Entry',          es:'Inscripción Carrera' },
  medicamentos2:    { pt:'Medicamentos',          br:'Medicamentos',         en:'Medications',         es:'Medicamentos' },
  alimentacao3:     { pt:'Alimentação',           br:'Alimentação',          en:'Feeding',             es:'Alimentación' },
  semTransacoes:    { pt:'Sem transacções',       br:'Sem transações',       en:'No transactions',     es:'Sin transacciones' },
  ano2:             { pt:'Ano',                   br:'Ano',                  en:'Year',                es:'Año' },
  mes:              { pt:'Mês',                   br:'Mês',                  en:'Month',               es:'Mes' },


  // ── Comunidade ──
  feed:             { pt:'Feed',               br:'Feed',              en:'Feed',              es:'Feed' },
  publicar:         { pt:'Publicar',           br:'Publicar',          en:'Post',              es:'Publicar' },
  novoPost:         { pt:'O que pensas?',      br:'O que pensa?',      en:"What's on your mind?", es:"¿Qué piensas?" },
  gostos:           { pt:'Gostos',             br:'Curtidas',          en:'Likes',             es:'Me gusta' },
  comentarios:      { pt:'Comentários',        br:'Comentários',       en:'Comments',          es:'Comentarios' },
  partilhar2:       { pt:'Partilhar',          br:'Compartilhar',      en:'Share',             es:'Compartir' },
  seguir:           { pt:'Seguir',             br:'Seguir',            en:'Follow',            es:'Seguir' },
  seguindo:         { pt:'A seguir',           br:'Seguindo',          en:'Following',         es:'Siguiendo' },
  seguidores:       { pt:'Seguidores',         br:'Seguidores',        en:'Followers',         es:'Seguidores' },
  ranking2:         { pt:'Ranking',            br:'Ranking',           en:'Ranking',           es:'Clasificación' },
  desafios:         { pt:'Desafios',           br:'Desafios',          en:'Challenges',        es:'Desafíos' },
  badges2:          { pt:'Badges',             br:'Badges',            en:'Badges',            es:'Insignias' },
  notificacoes2:    { pt:'Notificações',       br:'Notificações',      en:'Notifications',     es:'Notificaciones' },
  semPosts:         { pt:'Sem publicações',    br:'Sem publicações',   en:'No posts yet',      es:'Sin publicaciones' },
  escreverComent:   { pt:'Escreve um comentário...', br:'Escreva um comentário...', en:'Write a comment...', es:'Escribe un comentario...' },
  verMais:          { pt:'Ver mais',           br:'Ver mais',          en:'See more',          es:'Ver más' },
  grupos:           { pt:'Grupos',             br:'Grupos',            en:'Groups',            es:'Grupos' },
  membros2:         { pt:'Membros',            br:'Membros',           en:'Members',           es:'Miembros' },
  criarGrupo:       { pt:'Criar Grupo',        br:'Criar Grupo',       en:'Create Group',      es:'Crear Grupo' },
  entrarGrupo:      { pt:'Entrar',             br:'Entrar',            en:'Join',              es:'Unirse' },
  comunidadeVazia:  { pt:'A comunidade ainda está a crescer', br:'A comunidade está crescendo', en:'Community is growing', es:'La comunidad está creciendo' },

  // ── Mensagens ──
  mensagem:         { pt:'Mensagem',           br:'Mensagem',          en:'Message',           es:'Mensaje' },
  enviar:           { pt:'Enviar',             br:'Enviar',            en:'Send',              es:'Enviar' },
  novaMensagem:     { pt:'Nova Mensagem',      br:'Nova Mensagem',     en:'New Message',       es:'Nuevo Mensaje' },
  escreverMsg:      { pt:'Escreve uma mensagem...', br:'Escreva uma mensagem...', en:'Write a message...', es:'Escribe un mensaje...' },
  semMensagens:     { pt:'Sem mensagens',      br:'Sem mensagens',     en:'No messages',       es:'Sin mensajes' },
  conversas:        { pt:'Conversas',          br:'Conversas',         en:'Conversations',     es:'Conversaciones' },
  semConversas:     { pt:'Sem conversas ainda',br:'Sem conversas',     en:'No conversations',  es:'Sin conversaciones' },
  destinatario:     { pt:'Destinatário',       br:'Destinatário',      en:'Recipient',         es:'Destinatario' },
  ontem:            { pt:'Ontem',              br:'Ontem',             en:'Yesterday',         es:'Ayer' },

  // ── Marketplace ──
  novoAnuncio:      { pt:'Novo Anúncio',       br:'Novo Anúncio',      en:'New Listing',       es:'Nuevo Anuncio' },
  editAnuncio:      { pt:'Editar Anúncio',     br:'Editar Anúncio',    en:'Edit Listing',      es:'Editar Anuncio' },
  preco3:           { pt:'Preço (€)',           br:'Preço (€)',          en:'Price (€)',         es:'Precio (€)' },
  disponivel:       { pt:'Disponível',         br:'Disponível',        en:'Available',         es:'Disponible' },
  vendido2:         { pt:'Vendido',            br:'Vendido',           en:'Sold',              es:'Vendido' },
  reservado:        { pt:'Reservado',          br:'Reservado',         en:'Reserved',          es:'Reservado' },
  contactar:        { pt:'Contactar',          br:'Contactar',         en:'Contact',           es:'Contactar' },
  semAnuncios:      { pt:'Sem anúncios',       br:'Sem anúncios',      en:'No listings',       es:'Sin anuncios' },
  filtros2:         { pt:'Filtros',            br:'Filtros',           en:'Filters',           es:'Filtros' },
  ordenar:          { pt:'Ordenar',            br:'Ordenar',           en:'Sort',              es:'Ordenar' },
  maisRecente:      { pt:'Mais recente',       br:'Mais recente',      en:'Most recent',       es:'Más reciente' },
  menorPreco:       { pt:'Menor preço',        br:'Menor preço',       en:'Lowest price',      es:'Menor precio' },
  maiorPreco:       { pt:'Maior preço',        br:'Maior preço',       en:'Highest price',     es:'Mayor precio' },

  // ── Época ──
  gestaoEpoca:      { pt:'Gestão de Época',    br:'Gestão de Época',   en:'Season Management', es:'Gestión Temporada' },
  novaEpoca:        { pt:'Nova Época',         br:'Nova Época',        en:'New Season',        es:'Nueva Temporada' },
  epocaActiva:      { pt:'Época Activa',       br:'Época Ativa',       en:'Active Season',     es:'Temporada Activa' },
  inicioEpoca:      { pt:'Início da Época',    br:'Início da Época',   en:'Season Start',      es:'Inicio Temporada' },
  fimEpoca:         { pt:'Fim da Época',       br:'Fim da Época',      en:'Season End',        es:'Fin Temporada' },
  relatorioEpoca:   { pt:'Relatório de Época', br:'Relatório de Época',en:'Season Report',     es:'Informe Temporada' },
  gerarRelatorio:   { pt:'Gerar Relatório PDF',br:'Gerar Relatório PDF',en:'Generate PDF Report',es:'Generar Informe PDF' },
  estatisticas:     { pt:'Estatísticas',       br:'Estatísticas',      en:'Statistics',        es:'Estadísticas' },
  melhorPombo:      { pt:'Melhor Pombo',       br:'Melhor Pombo',      en:'Best Pigeon',       es:'Mejor Paloma' },
  semEpoca:         { pt:'Sem época activa',   br:'Sem época ativa',   en:'No active season',  es:'Sin temporada activa' },
  provasPorEpoca:   { pt:'Provas por Época',   br:'Corridas por Época',en:'Races per Season',  es:'Carreras por Temporada' },
  encerrarEpoca:    { pt:'Encerrar Época',     br:'Encerrar Época',    en:'Close Season',      es:'Cerrar Temporada' },

  // ── Relatórios ──
  relatorio:        { pt:'Relatório',          br:'Relatório',         en:'Report',            es:'Informe' },
  relatorios2:      { pt:'Relatórios',         br:'Relatórios',        en:'Reports',           es:'Informes' },
  gerarPDF:         { pt:'Gerar PDF',          br:'Gerar PDF',         en:'Generate PDF',      es:'Generar PDF' },
  relEpoca:         { pt:'Relatório de Época', br:'Relatório de Época',en:'Season Report',     es:'Informe Temporada' },
  relPombo:         { pt:'Ficha do Pombo',     br:'Ficha do Pombo',    en:'Pigeon Profile',    es:'Ficha de Paloma' },
  relFinanceiro:    { pt:'Relatório Financeiro',br:'Relatório Financeiro',en:'Financial Report',es:'Informe Financiero' },
  relSaude:         { pt:'Relatório de Saúde', br:'Relatório de Saúde',en:'Health Report',     es:'Informe de Salud' },
  periodoAnalise:   { pt:'Período de Análise', br:'Período de Análise',en:'Analysis Period',   es:'Período de Análisis' },
  incluir:          { pt:'Incluir',            br:'Incluir',           en:'Include',           es:'Incluir' },
  excluir2:         { pt:'Excluir',            br:'Excluir',           en:'Exclude',           es:'Excluir' },
  gerarRelatorio2:  { pt:'Gerar Relatório',    br:'Gerar Relatório',   en:'Generate Report',   es:'Generar Informe' },


  // ── Leilões ──
  leilao:           { pt:'Leilão',             br:'Leilão',            en:'Auction',           es:'Subasta' },
  leiloar:          { pt:'Leiloar',            br:'Leiloar',           en:'Auction',           es:'Subastar' },
  lanceActual:      { pt:'Lance actual',        br:'Lance atual',       en:'Current bid',       es:'Puja actual' },
  lanceMiniimo:     { pt:'Lance mínimo',        br:'Lance mínimo',      en:'Minimum bid',       es:'Puja mínima' },
  licitar:          { pt:'Licitar',             br:'Licitar',           en:'Bid',               es:'Pujar' },
  tempoRestante:    { pt:'Tempo restante',      br:'Tempo restante',    en:'Time remaining',    es:'Tiempo restante' },
  terminado:        { pt:'Terminado',           br:'Terminado',         en:'Ended',             es:'Terminado' },
  activos2:         { pt:'Activos',             br:'Ativos',            en:'Active',            es:'Activos' },
  meusLeiloes:      { pt:'Os meus leilões',     br:'Meus leilões',      en:'My auctions',       es:'Mis subastas' },
  semLeiloes:       { pt:'Sem leilões activos', br:'Sem leilões',       en:'No active auctions',es:'Sin subastas activas' },
  ultimosLances:    { pt:'Últimos lances',      br:'Últimos lances',    en:'Latest bids',       es:'Últimas pujas' },
  duracao4:         { pt:'Duração',             br:'Duração',           en:'Duration',          es:'Duración' },
  publicarLeilao:   { pt:'Publicar Leilão',     br:'Publicar Leilão',   en:'Publish Auction',   es:'Publicar Subasta' },

  // ── Ligas ──
  criarLiga:        { pt:'Criar Liga',          br:'Criar Liga',        en:'Create League',     es:'Crear Liga' },
  entrarLiga:       { pt:'Entrar por Código',   br:'Entrar por Código', en:'Join by Code',      es:'Unirse por Código' },
  codigoConvite:    { pt:'Código de convite',   br:'Código de convite', en:'Invite code',       es:'Código de invitación' },
  minhasLigas:      { pt:'As minhas',           br:'As minhas',         en:'My leagues',        es:'Mis ligas' },
  ligasOficiais:    { pt:'Ligas Oficiais CL',   br:'Ligas Oficiais CL', en:'Official CL Leagues',es:'Ligas Oficiales CL' },
  inscrever:        { pt:'Inscrever',           br:'Inscrever',         en:'Join',              es:'Inscribirse' },
  sincronizar:      { pt:'Sincronizar provas',  br:'Sincronizar corridas',en:'Sync races',      es:'Sincronizar carreras' },
  classificacao2:   { pt:'Classificação',       br:'Classificação',     en:'Standings',         es:'Clasificación' },
  jornadas:         { pt:'Jornadas',            br:'Jornadas',          en:'Rounds',            es:'Jornadas' },
  sistema:          { pt:'Sistema',             br:'Sistema',           en:'System',            es:'Sistema' },
  nMelhoresProvas:  { pt:'Melhores provas a contar',br:'Melhores corridas',en:'Best races to count',es:'Mejores carreras' },
  divisoes:         { pt:'Divisões',            br:'Divisões',          en:'Divisions',         es:'Divisiones' },
  promovidos:       { pt:'Promovidos',          br:'Promovidos',        en:'Promoted',          es:'Promovidos' },
  descidos:         { pt:'Descidos',            br:'Descidos',          en:'Relegated',         es:'Relegados' },
  semLigas:         { pt:'Sem ligas',           br:'Sem ligas',         en:'No leagues',        es:'Sin ligas' },

  // ── Analíticas ──
  analiticas2:      { pt:'Analíticas',          br:'Analíticas',        en:'Analytics',         es:'Analíticas' },
  desempenho:       { pt:'Desempenho',          br:'Desempenho',        en:'Performance',       es:'Rendimiento' },
  evolucao:         { pt:'Evolução',            br:'Evolução',          en:'Evolution',         es:'Evolución' },
  heatmap:          { pt:'Heatmap de Distâncias',br:'Heatmap de Distâncias',en:'Distance Heatmap',es:'Mapa de Distancias' },
  comparativo:      { pt:'Comparativo',         br:'Comparativo',       en:'Comparison',        es:'Comparativo' },
  mediaPercentil:   { pt:'Percentil Médio',     br:'Percentil Médio',   en:'Avg. Percentile',   es:'Percentil Medio' },
  taxaVitoria:      { pt:'Taxa de Vitória',     br:'Taxa de Vitória',   en:'Win Rate',          es:'Tasa de Victoria' },
  porEspecialidade: { pt:'Por Especialidade',   br:'Por Especialidade', en:'By Specialty',      es:'Por Especialidad' },
  porEpoca:         { pt:'Por Época',           br:'Por Época',         en:'By Season',         es:'Por Temporada' },
  benchmarkNacional:{ pt:'Benchmark Nacional',  br:'Benchmark Nacional',en:'National Benchmark',es:'Referencia Nacional' },
  individual:       { pt:'Individual',          br:'Individual',        en:'Individual',        es:'Individual' },
  clube2:           { pt:'Clube',               br:'Clube',             en:'Club',              es:'Club' },
  nacional:         { pt:'Nacional',            br:'Nacional',          en:'National',          es:'Nacional' },
  semDadosAnalitica:{ pt:'Sem dados suficientes',br:'Sem dados',        en:'Insufficient data', es:'Sin datos suficientes' },

  // ── Treinos ──
  treino:           { pt:'Treino',              br:'Treino',            en:'Training',          es:'Entrenamiento' },
  novoTreino2:      { pt:'Novo Treino',         br:'Novo Treino',       en:'New Training',      es:'Nuevo Entrenamiento' },
  editTreino:       { pt:'Editar Treino',       br:'Editar Treino',     en:'Edit Training',     es:'Editar Entrenamiento' },
  distTreino:       { pt:'Distância (km)',      br:'Distância (km)',    en:'Distance (km)',     es:'Distancia (km)' },
  pombosLancados:   { pt:'Pombos lançados',     br:'Pombos lançados',   en:'Pigeons released',  es:'Palomas lanzadas' },
  pombosRegressados:{ pt:'Pombos regressados',  br:'Pombos voltados',   en:'Pigeons returned',  es:'Palomas retornadas' },
  taxaRegresso:     { pt:'Taxa de regresso',    br:'Taxa de retorno',   en:'Return rate',       es:'Tasa de retorno' },
  condicaoMeteo:    { pt:'Condição Meteo',      br:'Condição Meteo',    en:'Weather Condition',  es:'Condición Meteo' },
  semTreinos:       { pt:'Sem treinos',         br:'Sem treinos',       en:'No training records',es:'Sin entrenamientos' },
  totalTreinos:     { pt:'Total de Treinos',    br:'Total de Treinos',  en:'Total Training',    es:'Total Entrenamientos' },
  kmPercorridos:    { pt:'km percorridos',      br:'km percorridos',    en:'km covered',        es:'km recorridos' },

  // ── Calendário ──
  novoEvento:       { pt:'Novo Evento',         br:'Novo Evento',       en:'New Event',         es:'Nuevo Evento' },
  editEvento:       { pt:'Editar Evento',       br:'Editar Evento',     en:'Edit Event',        es:'Editar Evento' },
  evento:           { pt:'Evento',              br:'Evento',            en:'Event',             es:'Evento' },
  eventos:          { pt:'Eventos',             br:'Eventos',           en:'Events',            es:'Eventos' },
  eventosHoje2:     { pt:'Eventos hoje',        br:'Eventos hoje',      en:"Today's events",   es:'Eventos hoy' },
  provaOficial:     { pt:'Prova Oficial',       br:'Corrida Oficial',   en:'Official Race',     es:'Carrera Oficial' },
  treino2:          { pt:'Treino',              br:'Treino',            en:'Training',          es:'Entrenamiento' },
  veterinario3:     { pt:'Veterinário',         br:'Veterinário',       en:'Veterinary',        es:'Veterinario' },
  outro:            { pt:'Outro',               br:'Outro',             en:'Other',             es:'Otro' },
  sincrFPC:         { pt:'Sincronizar FPC',     br:'Sincronizar FPC',   en:'Sync FPC',          es:'Sincronizar FPC' },
  calendarioFPC:    { pt:'Calendário FPC',      br:'Calendário FPC',    en:'FPC Calendar',      es:'Calendario FPC' },
  semEventos:       { pt:'Sem eventos',         br:'Sem eventos',       en:'No events',         es:'Sin eventos' },
  mes2:             { pt:'Mês',                 br:'Mês',               en:'Month',             es:'Mes' },
  semana3:          { pt:'Semana',              br:'Semana',            en:'Week',              es:'Semana' },
  dia2:             { pt:'Dia',                 br:'Dia',               en:'Day',               es:'Día' },
  anterior:         { pt:'Anterior',            br:'Anterior',          en:'Previous',          es:'Anterior' },
  proximo:          { pt:'Próximo',             br:'Próximo',           en:'Next',              es:'Siguiente' },
  local2:           { pt:'Local',               br:'Local',             en:'Location',          es:'Lugar' },
  horaInicio:       { pt:'Hora de Início',      br:'Hora de Início',    en:'Start Time',        es:'Hora de inicio' },


  // ── Clubes (Coletividades) ──
  coletividade:     { pt:'Coletividade',       br:'Coletividade',      en:'Club/Association',  es:'Asociación' },
  coletividades:    { pt:'Coletividades',       br:'Coletividades',     en:'Clubs',             es:'Asociaciones' },
  presidente:       { pt:'Presidente',          br:'Presidente',        en:'President',         es:'Presidente' },
  socio:            { pt:'Sócio',               br:'Sócio',             en:'Member',            es:'Socio' },
  socios:           { pt:'Sócios',              br:'Sócios',            en:'Members',           es:'Socios' },
  quotas:           { pt:'Quotas',              br:'Quotas',            en:'Fees',              es:'Cuotas' },
  comunicado:       { pt:'Comunicado',          br:'Comunicado',        en:'Announcement',      es:'Comunicado' },
  comunicados:      { pt:'Comunicados',         br:'Comunicados',       en:'Announcements',     es:'Comunicados' },
  novoComunicado:   { pt:'Novo Comunicado',     br:'Novo Comunicado',   en:'New Announcement',  es:'Nuevo Comunicado' },
  adicionarSocio:   { pt:'Adicionar Sócio',     br:'Adicionar Sócio',   en:'Add Member',        es:'Añadir Socio' },
  semSocios:        { pt:'Sem sócios',          br:'Sem sócios',        en:'No members',        es:'Sin socios' },
  semComunicados:   { pt:'Sem comunicados',     br:'Sem comunicados',   en:'No announcements',  es:'Sin comunicados' },
  pagoLabel:        { pt:'Pago',                br:'Pago',              en:'Paid',              es:'Pagado' },
  naoPagei:         { pt:'Não pago',            br:'Não pago',          en:'Unpaid',            es:'No pagado' },
  estatisticasClube:{ pt:'Estatísticas do Clube',br:'Estatísticas do Clube',en:'Club Statistics',es:'Estadísticas del Club' },

  // ── Rastreio de Forma ──
  rastreioForma:    { pt:'Rastreio de Forma',   br:'Rastreio de Forma', en:'Form Tracking',     es:'Seguimiento de Forma' },
  forma:            { pt:'Forma',               br:'Forma',             en:'Form',              es:'Forma' },
  emAlta:           { pt:'Em alta',             br:'Em alta',           en:'Rising',            es:'En alza' },
  emBaixa:          { pt:'Em baixa',            br:'Em baixa',          en:'Declining',         es:'En baja' },
  estavel:          { pt:'Estável',             br:'Estável',           en:'Stable',            es:'Estable' },
  melhorForma:      { pt:'Melhor forma',        br:'Melhor forma',      en:'Best form',         es:'Mejor forma' },
  piorForma:        { pt:'Pior forma',          br:'Pior forma',        en:'Worst form',        es:'Peor forma' },
  ultimas5:         { pt:'Últimas 5 provas',    br:'Últimas 5 corridas',en:'Last 5 races',      es:'Últimas 5 carreras' },
  tendencia:        { pt:'Tendência',           br:'Tendência',         en:'Trend',             es:'Tendencia' },
  semForma:         { pt:'Sem dados de forma',  br:'Sem dados de forma',en:'No form data',      es:'Sin datos de forma' },
  evolucaoForma:    { pt:'Evolução da Forma',   br:'Evolução da Forma', en:'Form Evolution',    es:'Evolución de la Forma' },

  // ── Exportação ──
  exportacaoDados:  { pt:'Exportação de Dados', br:'Exportação de Dados',en:'Data Export',      es:'Exportación de Datos' },
  backupCompleto:   { pt:'Backup completo',     br:'Backup completo',   en:'Full backup',       es:'Backup completo' },
  exportarTudo:     { pt:'Exportar tudo',       br:'Exportar tudo',     en:'Export all',        es:'Exportar todo' },
  exportarCSV:      { pt:'Exportar CSV',        br:'Exportar CSV',      en:'Export CSV',        es:'Exportar CSV' },
  dadosSeus:        { pt:'Os dados são teus',   br:'Os dados são seus', en:'Your data, your choice', es:'Tus datos, tu elección' },
  aExportar:        { pt:'A exportar...',        br:'A exportar...',     en:'Exporting...',      es:'Exportando...' },
  exportado:        { pt:'registos exportados', br:'registros exportados',en:'records exported', es:'registros exportados' },

  // ── Afiliados ──
  programa:         { pt:'Programa de Afiliados',br:'Programa de Afiliados',en:'Affiliate Program',es:'Programa de Afiliados' },
  comissao:         { pt:'Comissão',            br:'Comissão',          en:'Commission',        es:'Comisión' },
  referidos:        { pt:'Referidos',           br:'Referidos',         en:'Referrals',         es:'Referidos' },
  totalGanho:       { pt:'Total ganho',         br:'Total ganho',       en:'Total earned',      es:'Total ganado' },
  linkAfiliado:     { pt:'O teu link',          br:'O seu link',        en:'Your link',         es:'Tu enlace' },
  copiarLink:       { pt:'Copiar link',         br:'Copiar link',       en:'Copy link',         es:'Copiar enlace' },
  aderir:           { pt:'Aderir ao Programa',  br:'Aderir ao Programa',en:'Join Program',      es:'Unirse al Programa' },
  semReferidos:     { pt:'Sem referidos ainda', br:'Sem referidos',     en:'No referrals yet',  es:'Sin referidos aún' },
  pendente3:        { pt:'Pendente',            br:'Pendente',          en:'Pending',           es:'Pendiente' },
  pago2:            { pt:'Pago',                br:'Pago',              en:'Paid',              es:'Pagado' },
  materiaisMarketing:{ pt:'Mensagens prontas',  br:'Mensagens prontas', en:'Ready messages',    es:'Mensajes preparados' },

  // ── Meteorologia ──
  meteorologia2:    { pt:'Meteorologia',        br:'Meteorologia',      en:'Weather',           es:'Meteorología' },
  temperatura:      { pt:'Temperatura',         br:'Temperatura',       en:'Temperature',       es:'Temperatura' },
  vento:            { pt:'Vento',               br:'Vento',             en:'Wind',              es:'Viento' },
  humidade:         { pt:'Humidade',            br:'Umidade',           en:'Humidity',          es:'Humedad' },
  visibilidade:     { pt:'Visibilidade',        br:'Visibilidade',      en:'Visibility',        es:'Visibilidad' },
  precipitacao:     { pt:'Precipitação',        br:'Precipitação',      en:'Precipitation',     es:'Precipitación' },
  condicoesVoo:     { pt:'Condições de Voo',    br:'Condições de Voo',  en:'Flight Conditions',  es:'Condiciones de Vuelo' },
  excelente:        { pt:'Excelentes',          br:'Excelentes',        en:'Excellent',         es:'Excelentes' },
  boas:             { pt:'Boas',                br:'Boas',              en:'Good',              es:'Buenas' },
  moderadas:        { pt:'Moderadas',           br:'Moderadas',         en:'Moderate',          es:'Moderadas' },
  desfavoraveis:    { pt:'Desfavoráveis',       br:'Desfavoráveis',     en:'Unfavourable',      es:'Desfavorables' },
  previsao:         { pt:'Previsão',            br:'Previsão',          en:'Forecast',          es:'Pronóstico' },
  agora:            { pt:'Agora',               br:'Agora',             en:'Now',               es:'Ahora' },
  horasPorVir:      { pt:'Próximas horas',      br:'Próximas horas',    en:'Coming hours',      es:'Próximas horas' },
  semDadosMeteo:    { pt:'Sem dados meteorológicos', br:'Sem dados meteo', en:'No weather data', es:'Sin datos meteorológicos' },


  // ── Admin ──
  painel:           { pt:'Painel Admin',        br:'Painel Admin',      en:'Admin Panel',       es:'Panel Admin' },
  licencas2:        { pt:'Licenças',            br:'Licenças',          en:'Licenses',          es:'Licencias' },
  modulos2:         { pt:'Módulos',             br:'Módulos',           en:'Modules',           es:'Módulos' },
  beta2:            { pt:'Beta',                br:'Beta',              en:'Beta',              es:'Beta' },
  badges3:          { pt:'Badges',              br:'Badges',            en:'Badges',            es:'Insignias' },
  parcerias2:       { pt:'Parcerias',           br:'Parcerias',         en:'Partnerships',      es:'Asociaciones' },
  fundadores2:      { pt:'Fundadores',          br:'Fundadores',        en:'Founders',          es:'Fundadores' },
  utilizadores:     { pt:'Utilizadores',        br:'Utilizadores',      en:'Users',             es:'Usuarios' },
  planoLabel:       { pt:'Plano',               br:'Plano',             en:'Plan',              es:'Plan' },
  activar:          { pt:'Activar',             br:'Ativar',            en:'Activate',          es:'Activar' },
  desactivar:       { pt:'Desactivar',          br:'Desativar',         en:'Deactivate',        es:'Desactivar' },
  verificado2:      { pt:'Verificado',          br:'Verificado',        en:'Verified',          es:'Verificado' },
  semUtilizadores:  { pt:'Sem utilizadores',    br:'Sem utilizadores',  en:'No users',          es:'Sin usuarios' },

  // ── Pombais ──
  pombalNome:       { pt:'Nome do Pombal',      br:'Nome do Colombário',en:'Loft Name',         es:'Nombre del Palomar' },
  novoPombal:       { pt:'Novo Pombal',         br:'Novo Colombário',   en:'New Loft',          es:'Nuevo Palomar' },
  editPombal:       { pt:'Editar Pombal',       br:'Editar Colombário', en:'Edit Loft',         es:'Editar Palomar' },
  capacidade:       { pt:'Capacidade',          br:'Capacidade',        en:'Capacity',          es:'Capacidad' },
  localizacao:      { pt:'Localização',         br:'Localização',       en:'Location',          es:'Ubicación' },
  responsavel:      { pt:'Responsável',         br:'Responsável',       en:'Manager',           es:'Responsable' },
  semPombais:       { pt:'Sem pombais',         br:'Sem colombários',   en:'No lofts',          es:'Sin palomares' },
  pombaisLabel:     { pt:'Pombais',             br:'Colombários',       en:'Lofts',             es:'Palomares' },

  // ── Perfil ──
  editarPerfil:     { pt:'Editar Perfil',       br:'Editar Perfil',     en:'Edit Profile',      es:'Editar Perfil' },
  nomeCompleto:     { pt:'Nome completo',       br:'Nome completo',     en:'Full name',         es:'Nombre completo' },
  bio2:             { pt:'Bio',                 br:'Bio',               en:'Bio',               es:'Bio' },
  organizacao:      { pt:'Organização',         br:'Organização',       en:'Organisation',      es:'Organización' },
  perfilPublico2:   { pt:'Perfil público',      br:'Perfil público',    en:'Public profile',    es:'Perfil público' },
  slug2:            { pt:'URL do perfil',       br:'URL do perfil',     en:'Profile URL',       es:'URL del perfil' },
  avatarUrl:        { pt:'Foto de perfil',      br:'Foto de perfil',    en:'Profile photo',     es:'Foto de perfil' },
  perfilGuardado:   { pt:'Perfil guardado!',    br:'Perfil salvo!',     en:'Profile saved!',    es:'¡Perfil guardado!' },

  // ── Carteira ──
  carteira:         { pt:'Carteira CL',         br:'Carteira CL',       en:'CL Wallet',         es:'Billetera CL' },
  creditos:         { pt:'créditos',            br:'créditos',          en:'credits',           es:'créditos' },
  comprados:        { pt:'Comprados',           br:'Comprados',         en:'Purchased',         es:'Comprados' },
  ganhos:           { pt:'Ganhos',              br:'Ganhos',            en:'Earned',            es:'Ganados' },
  levantar:         { pt:'Levantar',            br:'Levantar',          en:'Withdraw',          es:'Retirar' },
  historico3:       { pt:'Histórico',           br:'Histórico',         en:'History',           es:'Historial' },
  comprar2:         { pt:'Comprar',             br:'Comprar',           en:'Buy',               es:'Comprar' },
  semMovimentos:    { pt:'Sem movimentos',      br:'Sem movimentos',    en:'No transactions',   es:'Sin movimientos' },
  minimoLevantar:   { pt:'Mínimo 20 créditos',  br:'Mínimo 20 créditos',en:'Minimum 20 credits',es:'Mínimo 20 créditos' },
  pedidoLevant:     { pt:'Pedido de levantamento registado!', br:'Pedido registado!', en:'Withdrawal request registered!', es:'¡Solicitud registrada!' },

  // ── Fundadores ──
  utilizadorFundador:{ pt:'Utilizador Fundador',br:'Utilizador Fundador',en:'Founder User',    es:'Usuario Fundador' },
  vagasRestantes:   { pt:'vagas restantes',     br:'vagas restantes',   en:'spots remaining',   es:'plazas restantes' },
  garantirVaga:     { pt:'Garantir vaga',       br:'Garantir vaga',     en:'Secure your spot',  es:'Asegurar plaza' },
  precoGarantido:   { pt:'Preço garantido para sempre', br:'Preço garantido para sempre', en:'Price locked forever', es:'Precio garantizado para siempre' },
  jaFundador:       { pt:'Já és Fundador!',     br:'Já é Fundador!',    en:"You're already a Founder!", es:"¡Ya eres Fundador!" },
  vagasEsgotadas:   { pt:'Vagas esgotadas',     br:'Vagas esgotadas',   en:'All spots taken',   es:'Plazas agotadas' },

  // ── Clubes Personalizados ──
  clubePersonal:    { pt:'Clube',               br:'Clube',             en:'Club',              es:'Club' },
  clubesPersonais:  { pt:'Clubes & Equipes',    br:'Clubes & Equipes',  en:'Clubs & Teams',     es:'Clubes y Equipos' },
  criarClube:       { pt:'Criar Clube',         br:'Criar Clube',       en:'Create Club',       es:'Crear Club' },
  entrarClube:      { pt:'Entrar por Código',   br:'Entrar por Código', en:'Join by Code',      es:'Unirse por Código' },
  meusClubess:      { pt:'Os meus',             br:'Os meus',           en:'My clubs',          es:'Mis clubes' },
  clubesPublicos:   { pt:'Clubes públicos',     br:'Clubes públicos',   en:'Public clubs',      es:'Clubes públicos' },
  emblema:          { pt:'Emblema',             br:'Emblema',           en:'Emblem',            es:'Emblema' },
  regiao:           { pt:'Região',              br:'Região',            en:'Region',            es:'Región' },
  semClubess:       { pt:'Sem clubes',          br:'Sem clubes',        en:'No clubs',          es:'Sin clubes' },
  ranking3:         { pt:'Ranking',             br:'Ranking',           en:'Ranking',           es:'Clasificación' },
  sairClube:        { pt:'Sair do clube',       br:'Sair do clube',     en:'Leave club',        es:'Salir del club' },

  // ── Liga de Clubes ──
  ligaClubes:       { pt:'Liga de Clubes',      br:'Liga de Clubes',    en:'Club League',       es:'Liga de Clubes' },
  modoCampeoes:     { pt:'Modo Campeões',       br:'Modo Campeões',     en:'Champions Mode',    es:'Modo Campeones' },
  challenge2:       { pt:'Challenge',           br:'Challenge',         en:'Challenge',         es:'Challenge' },
  faseGrupos:       { pt:'Fase de Grupos',      br:'Fase de Grupos',    en:'Group Stage',       es:'Fase de Grupos' },
  quartos:          { pt:'Quartos-de-Final',    br:'Quartos-de-Final',  en:'Quarter Finals',    es:'Cuartos de Final' },
  meias:            { pt:'Meias-Finais',        br:'Meias-Finais',      en:'Semi Finals',       es:'Semifinales' },
  final2:           { pt:'Final',               br:'Final',             en:'Final',             es:'Final' },
  inscricoes2:      { pt:'Inscrições abertas',  br:'Inscrições abertas',en:'Open for registration',es:'Inscripciones abiertas' },
  inscreverClube:   { pt:'Inscreve o teu clube',br:'Inscreva seu clube',en:'Register your club',es:'Inscribe tu club' },
  confrontos:       { pt:'Confrontos',          br:'Confrontos',        en:'Matchups',          es:'Enfrentamientos' },
  semCompet:        { pt:'Sem competições',     br:'Sem competições',   en:'No competitions',   es:'Sin competiciones' },

  // ── Conquistas ──
  todasConquistas:  { pt:'Todas',               br:'Todas',             en:'All',               es:'Todas' },
  desbloqueadas:    { pt:'desbloqueadas',       br:'desbloqueadas',     en:'unlocked',          es:'desbloqueadas' },
  bloqueada:        { pt:'Bloqueada',           br:'Bloqueada',         en:'Locked',            es:'Bloqueada' },
  semConqCateg:     { pt:'Sem conquistas nesta categoria', br:'Sem conquistas', en:'No achievements in this category', es:'Sin logros en esta categoría' },

  inativo:        { pt:'Inactivo',       br:'Inativo',         en:'Inactive',        es:'Inactivo' },
  pendente:       { pt:'Pendente',       br:'Pendente',        en:'Pending',         es:'Pendiente' },
  concluido:      { pt:'Concluído',      br:'Concluído',       en:'Completed',       es:'Completado' },
  masculino:      { pt:'Macho',          br:'Macho',           en:'Male',            es:'Macho' },
  feminino:       { pt:'Fêmea',          br:'Fêmea',           en:'Female',          es:'Hembra' },
  // ── Campos comuns ──
  nome:           { pt:'Nome',           br:'Nome',            en:'Name',            es:'Nombre' },
  data:           { pt:'Data',           br:'Data',            en:'Date',            es:'Fecha' },
  local:          { pt:'Local',          br:'Local',           en:'Location',        es:'Lugar' },
  distancia:      { pt:'Distância',      br:'Distância',       en:'Distance',        es:'Distancia' },
  obs:            { pt:'Observações',    br:'Observações',     en:'Notes',           es:'Observaciones' },
  cor:            { pt:'Cor',            br:'Cor',             en:'Colour',          es:'Color' },
  sexo:           { pt:'Sexo',           br:'Sexo',            en:'Sex',             es:'Sexo' },
  foto:           { pt:'Foto',           br:'Foto',            en:'Photo',           es:'Foto' },
  descricao:      { pt:'Descrição',      br:'Descrição',       en:'Description',     es:'Descripción' },
  // ── Mensagens comuns ──
  semDados:       { pt:'Sem dados',      br:'Sem dados',       en:'No data',         es:'Sin datos' },
  carregando:     { pt:'A carregar...',  br:'Carregando...',   en:'Loading...',      es:'Cargando...' },
  erro:           { pt:'Erro',           br:'Erro',            en:'Error',           es:'Error' },
  sucesso:        { pt:'Guardado!',      br:'Salvo!',          en:'Saved!',          es:'Guardado!' },
  sair:           { pt:'Sair',           br:'Sair',            en:'Sign out',        es:'Salir' },
}

export const IDIOMAS = [
  { code:'pt', label:'🇵🇹 PT', nome:'Português (PT)' },
  { code:'br', label:'🇧🇷 BR', nome:'Português (BR)' },
  { code:'en', label:'🇬🇧 EN', nome:'English' },
  { code:'es', label:'🇪🇸 ES', nome:'Español' },
]

export const IdiomaContext = createContext('pt')

export function useIdioma() {
  const idioma = useContext(IdiomaContext)
  const t = (chave) => TRADUCOES[chave]?.[idioma] || TRADUCOES[chave]?.pt || chave
  return { idioma, t, isBR: idioma==='br', isEN: idioma==='en', isES: idioma==='es', isPT: idioma==='pt' }
}

export function useIdiomaState() {
  const [idioma, setIdioma] = useState(() => {
    try { return localStorage.getItem('cl_idioma') || 'pt' } catch { return 'pt' }
  })
  const trocar = (novo) => {
    setIdioma(novo)
    try { localStorage.setItem('cl_idioma', novo) } catch {}
  }
  return { idioma, setIdioma: trocar }
}
